/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.11.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "inertia4j-spring-example"

includeBuild("../inertia4j") {
    dependencySubstitution {
        substitute(module("io.github.inertia4j:inertia4j-spring-boot-4")).using(project(":inertia4j.spring-boot-4"))
    }
}